In [1]:
import pandas as pd
import numpy as np

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [3]:
TablaMarClient= pd.read_csv(f'CR_Nodos2.csv',sep=';')
TablaChurn=pd.read_csv(f'N3_Tomas_Rojas.csv',sep=';')

In [4]:
TablaMarClient.sample(5)

          NODO  MARCACIONES  CLIENTES  CONTACT  MES  ANIO  DIA       FECHA
49396   1B3014           16       104    15.38   12  2020    1  2020-12-01
41827    BSM2D            2        12    16.66   11  2020    1  2020-11-01
84818      AHG            7        16    43.75    2  2021    1  2021-02-01
133059     QP2          132       497    26.55    5  2021    1  2021-05-01
186007     ARV           69       275    25.09    8  2021    1  2021-08-01

In [5]:
len(TablaMarClient)

186849

In [6]:
TablaMarClient.size

1494792

In [7]:
len(TablaMarClient.columns)

8

In [8]:
TablaMarClient.describe()

,MARCACIONES,CLIENTES,CONTACT,MES,ANIO,DIA
count,186849.000000,186849.000000,186849.000000,186849.000000,186849.000000,186849.0
mean,39.666040,208.058432,20.722029,6.483835,2020.673341,1.0
std,47.968487,182.478957,26.249678,3.430184,0.468993,0.0
min,1.000000,1.000000,0.256000,1.000000,2020.000000,1.0
25%,10.000000,65.000000,10.930000,4.000000,2020.000000,1.0
50%,25.000000,162.000000,16.270000,6.000000,2021.000000,1.0
75%,53.000000,310.000000,24.270000,9.000000,2021.000000,1.0
max,1477.000000,4679.000000,6700.000000,12.000000,2021.000000,1.0

In [9]:
# INDEX

In [10]:
TablaMarClient.set_index(['NODO'],inplace=True)

In [11]:
TablaMarClient.head()

      MARCACIONES  CLIENTES  CONTACT  MES  ANIO  DIA       FECHA
NODO
VE2           139       286    48.60    9  2020    1  2020-09-01
CQ59            3        15    20.00    9  2020    1  2020-09-01
BLT           169       716    23.60    9  2020    1  2020-09-01
ORQ           212       588    36.05    9  2020    1  2020-09-01
AT91            4        12    33.33    9  2020    1  2020-09-01

In [12]:
TablaMarClient.reset_index(inplace=True)

In [13]:
# Filtros

In [14]:
selCol=['CONTACT','CLIENTES']

In [15]:
TablaMarClient['suma']=TablaMarClient[selCol].sum(axis=1)

In [16]:
TablaMarClient.suma

0         334.600
1          35.000
2         739.600
3         624.050
4          45.330
           ...
186844    493.711
186845    212.857
186846    250.065
186847    284.220
186848     91.409
Name: suma, Length: 186849, dtype: float64

In [17]:
TablaMarClient.loc['N1C']

KeyError: 'N1C'

In [ ]:
tablaPrueba=TablaMarClient[(TablaMarClient['MARCACIONES']>10)&(TablaMarClient['CLIENTES']>200)]

In [18]:
tablaPrueba

NameError: name 'tablaPrueba' is not defined

In [19]:
TablaMarClient[['MARCACIONES','FECHA']].reset_index()

         index  MARCACIONES       FECHA
0            0          139  2020-09-01
1            1            3  2020-09-01
2            2          169  2020-09-01
3            3          212  2020-09-01
4            4            4  2020-09-01
...        ...          ...         ...
186844  186844           47  2021-08-01
186845  186845            6  2021-08-01
186846  186846           10  2021-08-01
186847  186847           20  2021-08-01
186848  186848            3  2021-08-01

[186849 rows x 3 columns]

In [20]:
TablaMarClient[TablaMarClient['MARCACIONES']>10]['MARCACIONES'].reset_index().groupby('NODO').quantile(0.10)

KeyError: 'NODO'

In [21]:
TablaMarClient[['MARCACIONES','FECHA']].reset_index().groupby('FECHA').quantile(0.10)

               index  MARCACIONES
FECHA
2020-09-01    1530.8          5.0
2020-10-01   16838.5          5.0
2020-11-01   32125.3          4.0
2020-12-01   47331.6          3.0
2021-01-01   62573.7          4.0
2021-02-01   77960.1          4.0
2021-03-01   93433.0          4.0
2021-04-01  109014.0          3.0
2021-05-01  124694.2          3.0
2021-06-01  140458.0          3.0
2021-07-01  156244.6          3.0
2021-08-01  172205.9          3.0

In [22]:
#COLUMNA CALCULADA CON CONDICIONAL
TablaMarClient['Distrito']=np.where(TablaMarClient['MARCACIONES']%2==1,'BOGOTA','MEDELLIN')

In [23]:
TablaMarClient

,NODO,MARCACIONES,CLIENTES,CONTACT,MES,ANIO,DIA,FECHA,suma,Distrito
0,VE2,139,286,48.600,9,2020,1,2020-09-01,334.600,BOGOTA
1,CQ59,3,15,20.000,9,2020,1,2020-09-01,35.000,BOGOTA
2,BLT,169,716,23.600,9,2020,1,2020-09-01,739.600,BOGOTA
3,ORQ,212,588,36.050,9,2020,1,2020-09-01,624.050,MEDELLIN
4,AT91,4,12,33.330,9,2020,1,2020-09-01,45.330,MEDELLIN
...,...,...,...,...,...,...,...,...,...,...
186844,IA2,47,484,9.711,8,2021,1,2021-08-01,493.711,BOGOTA
186845,HSPEDR,6,210,2.857,8,2021,1,2021-08-01,212.857,MEDELLIN
186846,HSUARE,10,246,4.065,8,2021,1,2021-08-01,250.065,MEDELLIN
186847,SEE,20,277,7.220,8,2021,1,2021-08-01,284.220,MEDELLIN
186848,C4T,3,88,3.409,8,2021,1,2021-08-01,91.409,BOGOTA

In [24]:
# tipos datos

In [25]:
Percentiles_Distrito=TablaMarClient[['MARCACIONES','Distrito']].reset_index().groupby('Distrito').quantile(0.20)
Percentiles_Distrito.columns=['p20']

ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements

In [26]:
Percentiles_Distrito

            index  MARCACIONES
Distrito
BOGOTA    37543.2          7.0
MEDELLIN  37203.4          8.0

In [27]:
Percentiles_Distrito['p60']=TablaMarClient[['MARCACIONES','Distrito']].reset_index().groupby('Distrito').quantile(0.60)

ValueError: Wrong number of items passed 2, placement implies 1

In [28]:
TablaMarClient=TablaMarClient.merge(Percentiles_Distrito, left_on='Distrito', right_index=True, how='left')
TablaMarClient

,NODO,MARCACIONES_x,CLIENTES,CONTACT,MES,ANIO,DIA,FECHA,suma,Distrito,index,MARCACIONES_y
0,VE2,139,286,48.600,9,2020,1,2020-09-01,334.600,BOGOTA,37543.2,7.0
1,CQ59,3,15,20.000,9,2020,1,2020-09-01,35.000,BOGOTA,37543.2,7.0
2,BLT,169,716,23.600,9,2020,1,2020-09-01,739.600,BOGOTA,37543.2,7.0
3,ORQ,212,588,36.050,9,2020,1,2020-09-01,624.050,MEDELLIN,37203.4,8.0
4,AT91,4,12,33.330,9,2020,1,2020-09-01,45.330,MEDELLIN,37203.4,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186844,IA2,47,484,9.711,8,2021,1,2021-08-01,493.711,BOGOTA,37543.2,7.0
186845,HSPEDR,6,210,2.857,8,2021,1,2021-08-01,212.857,MEDELLIN,37203.4,8.0
186846,HSUARE,10,246,4.065,8,2021,1,2021-08-01,250.065,MEDELLIN,37203.4,8.0
186847,SEE,20,277,7.220,8,2021,1,2021-08-01,284.220,MEDELLIN,37203.4,8.0
186848,C4T,3,88,3.409,8,2021,1,2021-08-01,91.409,BOGOTA,37543.2,7.0

In [29]:
TablaMarClient['tipoChurn']=np.where(TablaMarClient['MARCACIONES']<TablaMarClient['p20'],'BUENO',np.where(TablaMarClient['MARCACIONES']<TablaMarClient['p60'],'REGULAR','MALO'))
TablaMarClient

KeyError: 'MARCACIONES'

In [30]:
TablaMarClient[TablaMarClient['tipoChurn']=='MALO']

KeyError: 'tipoChurn'

In [31]:
TablaMarClient['tipoFinal']=TablaMarClient['Distrito']+'---'+TablaMarClient['tipoChurn']

KeyError: 'tipoChurn'

In [32]:
TablaMarClient

,NODO,MARCACIONES_x,CLIENTES,CONTACT,MES,ANIO,DIA,FECHA,suma,Distrito,index,MARCACIONES_y
0,VE2,139,286,48.600,9,2020,1,2020-09-01,334.600,BOGOTA,37543.2,7.0
1,CQ59,3,15,20.000,9,2020,1,2020-09-01,35.000,BOGOTA,37543.2,7.0
2,BLT,169,716,23.600,9,2020,1,2020-09-01,739.600,BOGOTA,37543.2,7.0
3,ORQ,212,588,36.050,9,2020,1,2020-09-01,624.050,MEDELLIN,37203.4,8.0
4,AT91,4,12,33.330,9,2020,1,2020-09-01,45.330,MEDELLIN,37203.4,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186844,IA2,47,484,9.711,8,2021,1,2021-08-01,493.711,BOGOTA,37543.2,7.0
186845,HSPEDR,6,210,2.857,8,2021,1,2021-08-01,212.857,MEDELLIN,37203.4,8.0
186846,HSUARE,10,246,4.065,8,2021,1,2021-08-01,250.065,MEDELLIN,37203.4,8.0
186847,SEE,20,277,7.220,8,2021,1,2021-08-01,284.220,MEDELLIN,37203.4,8.0
186848,C4T,3,88,3.409,8,2021,1,2021-08-01,91.409,BOGOTA,37543.2,7.0

In [33]:
TablaMarClient[['Distrito','tipoFinal']].value_counts()

KeyError: "['tipoFinal'] not in index"

In [34]:
TablaMarClient.drop(columns=['MES','ANIO'],inplace=True)

In [35]:
resultadoFinal.to_csv('resultadoPrediciones.csv')

NameError: name 'resultadoFinal' is not defined

In [45]:
from __future__ import print_function  # for Python2
import sys

memoria=pd.DataFrame(columns=['variable','peso'])
local_vars = list(locals().items())
for var, obj in local_vars:
    #print(var, sys.getsizeof(obj))
    row={'variable':var ,'peso':sys.getsizeof(obj)}
    memoria=memoria.append(row, ignore_index=True)
memoria.sort_values('peso',ascending=False).head(10)

          variable      peso
29      TablaChurn  53478238
60             _23  46310903
28  TablaMarClient  46310903
68             _28  46310903
73             _32  46310903
54             _19  15508611
50             _16   1494936
94             _43      9622
16              __      9622
92             _42      9022

          variable      peso
29      TablaChurn  53478238
16              __  46310903
60             _23  46310903
73             _32  46310903
28  TablaMarClient  46310903
..             ...       ...
33              _5        28
4         __spec__        16
87         memoria        16
3       __loader__        16
2      __package__        16

[91 rows x 2 columns]